apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: dispatcher-service
        image: ghcr.io/zzzang12-cns/dispatcher-service
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9003
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: config-service.default.svc.cluster.local
        - name: SPRING_RABBITMQ_HOST
          value: polar-rabbitmq